In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
from matplotlib import pyplot as plt

In [2]:
df1 = pd.read_csv("Traffic_Volume_Counts__2011-2012_.csv")

In [19]:
df1 = df1.rename({'GIS ID': 'Segment ID'}, axis=1)

In [20]:
df1.head()

,ID,Segment ID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,10:00-11:00AM,11:00-12:00PM,12:00-1:00PM,1:00-2:00PM,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM
0,1,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/09/2012,20,10,11,14,13,20,34,66,100,52,68,85,85.0,94.0,104.0,105.0,147.0,120.0,91.0,83.0,74.0,49.0,42.0,42.0
1,2,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/10/2012,21,16,8,6,13,13,31,70,67,45,57,67,73.0,95.0,102.0,98.0,133.0,131.0,95.0,73.0,70.0,63.0,42.0,35.0
2,3,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/11/2012,27,14,6,5,12,16,34,75,69,71,67,70,90.0,89.0,115.0,115.0,130.0,143.0,106.0,89.0,68.0,64.0,56.0,43.0
3,4,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/12/2012,22,7,7,8,11,12,33,75,89,66,70,60,105.0,103.0,71.0,127.0,122.0,144.0,122.0,76.0,64.0,58.0,64.0,43.0
4,5,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/13/2012,31,17,7,5,13,28,29,68,84,64,83,89,88.0,113.0,113.0,126.0,133.0,135.0,102.0,106.0,58.0,58.0,55.0,54.0

In [21]:
df2 = pd.read_csv("Traffic_Volume_Counts__2012-2013_.csv")

In [22]:
df2.head()

,ID,Segment ID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,10:00-11:00AM,11:00-12:00PM,12:00-1:00PM,1:00-2:00PM,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM
0,1,2153,HUGUENOT AVE,WOODROW RD,STAFFORD AVE,NB,02/02/2013,106,74,45.0,29.0,29,45.0,71,145.0,213.0,278,387,335,406,411,371,398,324,394,379,329,249,197,187,169
1,1,2153,HUGUENOT AVE,WOODROW RD,STAFFORD AVE,NB,02/03/2013,109,74,55.0,37.0,26,25.0,47,74.0,111.0,204,249,351,374,350,308,291,313,253,242,217,210,144,125,79
2,1,2153,HUGUENOT AVE,WOODROW RD,STAFFORD AVE,NB,02/04/2013,36,28,11.0,16.0,32,108.0,168,418.0,493.0,263,282,307,304,328,426,425,419,469,425,358,224,185,132,74
3,1,2153,HUGUENOT AVE,WOODROW RD,STAFFORD AVE,NB,02/05/2013,42,28,16.0,12.0,34,109.0,193,397.0,499.0,241,255,294,310,382,393,479,441,476,446,424,305,219,171,76
4,1,2153,HUGUENOT AVE,WOODROW RD,STAFFORD AVE,NB,02/06/2013,35,38,12.0,14.0,31,98.0,195,372.0,490.0,297,260,283,334,324,383,384,391,369,401,338,236,186,123,76

In [23]:
df3 = pd.read_csv("Traffic_Volume_Counts__2014-2018_.csv")

In [24]:
df3.head()

,ID,Segment ID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,10:00-11:00AM,11:00-12:00PM,12:00-1:00PM,1:00-2:00PM,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM
0,2,70376,3 Avenue,East 154 Street,East 155 Street,NB,09/13/2014,204.0,177.0,133.0,126.0,141.0,134.0,121.0,180.0,223.0,272.0,386.0,339.0,513,506,520,611,573,546,582,528,432,328,282,240
1,2,70376,3 Avenue,East 155 Street,East 154 Street,SB,09/13/2014,140.0,51.0,128.0,116.0,144.0,146.0,153.0,219.0,226.0,273.0,317.0,325.0,403,414,379,376,329,362,418,335,282,247,237,191
2,56,176365,Bedford Park Boulevard,Grand Concourse,Valentine Avenue,EB,09/13/2014,94.0,73.0,65.0,61.0,64.0,73.0,65.0,113.0,169.0,210.0,182.0,245.0,244,233,280,272,264,236,213,190,199,183,147,103
3,56,176365,Bedford Park Boulevard,Grand Concourse,Valentine Avenue,WB,09/13/2014,88.0,82.0,75.0,60.0,65.0,67.0,71.0,142.0,198.0,212.0,205.0,237.0,257,245,237,276,223,240,217,198,186,162,157,103
4,62,147673,Broadway,West 242 Street,240 Street,SB,09/13/2014,255.0,209.0,149.0,148.0,128.0,136.0,199.0,354.0,473.0,567.0,634.0,781.0,785,779,732,809,707,675,641,556,546,465,425,324

In [25]:
pdList = [df1, df2, df3]  # List of your dataframes
new_df = pd.concat(pdList)

In [26]:
new_df.head()

,ID,Segment ID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,10:00-11:00AM,11:00-12:00PM,12:00-1:00PM,1:00-2:00PM,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM
0,1,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/09/2012,20.0,10.0,11.0,14.0,13.0,20.0,34.0,66.0,100.0,52.0,68.0,85.0,85.0,94.0,104.0,105.0,147.0,120.0,91.0,83.0,74.0,49.0,42.0,42.0
1,2,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/10/2012,21.0,16.0,8.0,6.0,13.0,13.0,31.0,70.0,67.0,45.0,57.0,67.0,73.0,95.0,102.0,98.0,133.0,131.0,95.0,73.0,70.0,63.0,42.0,35.0
2,3,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/11/2012,27.0,14.0,6.0,5.0,12.0,16.0,34.0,75.0,69.0,71.0,67.0,70.0,90.0,89.0,115.0,115.0,130.0,143.0,106.0,89.0,68.0,64.0,56.0,43.0
3,4,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/12/2012,22.0,7.0,7.0,8.0,11.0,12.0,33.0,75.0,89.0,66.0,70.0,60.0,105.0,103.0,71.0,127.0,122.0,144.0,122.0,76.0,64.0,58.0,64.0,43.0
4,5,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/13/2012,31.0,17.0,7.0,5.0,13.0,28.0,29.0,68.0,84.0,64.0,83.0,89.0,88.0,113.0,113.0,126.0,133.0,135.0,102.0,106.0,58.0,58.0,55.0,54.0

In [27]:
df1.shape

(3393, 31)

In [28]:
df2.shape

(5945, 31)

In [29]:
df3.shape

(21448, 31)

In [30]:
new_df.shape

(30786, 31)

In [14]:
new_df.dtypes

ID                 int64
GIS ID           float64
Roadway Name      object
From              object
To                object
Direction         object
Date              object
12:00-1:00 AM    float64
1:00-2:00AM      float64
2:00-3:00AM      float64
3:00-4:00AM      float64
4:00-5:00AM      float64
5:00-6:00AM      float64
6:00-7:00AM      float64
7:00-8:00AM      float64
8:00-9:00AM      float64
9:00-10:00AM     float64
10:00-11:00AM    float64
11:00-12:00PM    float64
12:00-1:00PM     float64
1:00-2:00PM      float64
2:00-3:00PM      float64
3:00-4:00PM      float64
4:00-5:00PM      float64
5:00-6:00PM      float64
6:00-7:00PM      float64
7:00-8:00PM      float64
8:00-9:00PM      float64
9:00-10:00PM     float64
10:00-11:00PM    float64
11:00-12:00AM    float64
Segment ID       float64
dtype: object

In [31]:
new_df['year'] = pd.DatetimeIndex(new_df['Date']).year
# df['month'] = pd.DatetimeIndex(df['ArrivalDate']).month

In [32]:
new_df

,ID,Segment ID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,10:00-11:00AM,11:00-12:00PM,12:00-1:00PM,1:00-2:00PM,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM,year
0,1,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/09/2012,20.0,10.0,11.0,14.0,13.0,20.0,34.0,66.0,100.0,52.0,68.0,85.0,85.0,94.0,104.0,105.0,147.0,120.0,91.0,83.0,74.0,49.0,42.0,42.0,2012
1,2,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/10/2012,21.0,16.0,8.0,6.0,13.0,13.0,31.0,70.0,67.0,45.0,57.0,67.0,73.0,95.0,102.0,98.0,133.0,131.0,95.0,73.0,70.0,63.0,42.0,35.0,2012
2,3,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/11/2012,27.0,14.0,6.0,5.0,12.0,16.0,34.0,75.0,69.0,71.0,67.0,70.0,90.0,89.0,115.0,115.0,130.0,143.0,106.0,89.0,68.0,64.0,56.0,43.0,2012
3,4,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/12/2012,22.0,7.0,7.0,8.0,11.0,12.0,33.0,75.0,89.0,66.0,70.0,60.0,105.0,103.0,71.0,127.0,122.0,144.0,122.0,76.0,64.0,58.0,64.0,43.0,2012
4,5,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/13/2012,31.0,17.0,7.0,5.0,13.0,28.0,29.0,68.0,84.0,64.0,83.0,89.0,88.0,113.0,113.0,126.0,133.0,135.0,102.0,106.0,58.0,58.0,55.0,54.0,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21443,366,26557,Mc Donald Avenue,Elmwood Avenue,47 Street,EB,04/15/2018,149.0,81.0,59.0,45.0,42.0,37.0,54.0,104.0,136.0,216.0,283.0,299.0,286.0,269.0,256.0,320.0,291.0,266.0,256.0,251.0,228.0,202.0,197.0,154.0,2018
21444,366,26557,Mc Donald Avenue,Elmwood Avenue,47 Street,WB,04/15/2018,169.0,95.0,86.0,56.0,45.0,59.0,98.0,168.0,259.0,410.0,411.0,465.0,516.0,509.0,523.0,465.0,531.0,436.0,446.0,374.0,311.0,289.0,273.0,170.0,2018
21445,367,42098,Utica Avenue,Lenox Road,Linden Boulevard,NB,04/15/2018,415.0,339.0,239.0,185.0,212.0,158.0,138.0,249.0,285.0,386.0,393.0,481.0,547.0,551.0,631.0,618.0,520.0,564.0,455.0,481.0,425.0,404.0,317.0,280.0,2018
21446,367,42098,Utica Avenue,Lenox Road,Linden Boulevard,SB,04/15/2018,347.0,276.0,225.0,191.0,254.0,210.0,216.0,246.0,282.0,414.0,485.0,512.0,502.0,487.0,527.0,521.0,519.0,466.0,493.0,495.0,401.0,391.0,309.0,270.0,2018
21447,368,37379,Madison Avenue,East 73 Street,East 74 Street,NB,04/15/2018,1025.0,577.0,435.0,358.0,303.0,217.0,347.0,511.0,587.0,929.0,1255.0,1216.0,1187.0,1150.0,1270.0,1350.0,1248.0,1306.0,1366.0,1131.0,1060.0,859.0,962.0,836.0,2018

In [60]:
new_df[(new_df['Segment ID']  == 9014615)&(new_df['year']  == 2014 ) ]

,ID,Segment ID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,10:00-11:00AM,11:00-12:00PM,12:00-1:00PM,1:00-2:00PM,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM,year
27,125,9014615,East Fordham Road,Southern Boulevard,Bronx River Parkway,WB,09/13/2014,952.0,816.0,610.0,336.0,331.0,367.0,673.0,1106.0,1526.0,1651.0,1646.0,2080.0,2143.0,1970.0,1994.0,2045.0,1881.0,2086.0,1797.0,1829.0,1721.0,1348.0,1210.0,1012.0,2014
99,125,9014615,East Fordham Road,Southern Boulevard,Bronx River Parkway,WB,09/14/2014,880.0,776.0,529.0,434.0,390.0,343.0,449.0,670.0,944.0,1119.0,1521.0,1729.0,1713.0,1739.0,1807.0,1856.0,1779.0,1839.0,1742.0,1696.0,1625.0,1209.0,945.0,723.0,2014
171,125,9014615,East Fordham Road,Southern Boulevard,Bronx River Parkway,WB,09/15/2014,486.0,272.0,190.0,184.0,279.0,545.0,1991.0,3594.0,3546.0,2361.0,1726.0,1736.0,1692.0,1727.0,2199.0,2331.0,2220.0,2387.0,1936.0,1612.0,1300.0,907.0,878.0,743.0,2014
242,125,9014615,East Fordham Road,Southern Boulevard,Bronx River Parkway,WB,09/16/2014,412.0,311.0,159.0,162.0,238.0,561.0,2039.0,3386.0,2903.0,3119.0,1859.0,1508.0,1543.0,1654.0,1893.0,2151.0,2475.0,2184.0,1949.0,1693.0,1322.0,976.0,810.0,668.0,2014
314,125,9014615,East Fordham Road,Southern Boulevard,Bronx River Parkway,WB,09/17/2014,465.0,259.0,130.0,107.0,191.0,403.0,2037.0,3590.0,3477.0,2123.0,1880.0,1717.0,1757.0,1784.0,2072.0,2353.0,2335.0,2414.0,1964.0,1709.0,1297.0,1065.0,849.0,897.0,2014
387,125,9014615,East Fordham Road,Southern Boulevard,Bronx River Parkway,WB,09/18/2014,553.0,302.0,196.0,161.0,224.0,544.0,2041.0,3578.0,3328.0,2266.0,1840.0,1764.0,1718.0,1806.0,2054.0,2256.0,2425.0,2336.0,2089.0,1942.0,1388.0,1067.0,751.0,635.0,2014
458,125,9014615,East Fordham Road,Southern Boulevard,Bronx River Parkway,WB,09/19/2014,422.0,318.0,192.0,158.0,244.0,513.0,1975.0,3590.0,3304.0,2189.0,1836.0,1805.0,1897.0,1935.0,2176.0,2439.0,2575.0,2595.0,2606.0,2074.0,1684.0,1357.0,1202.0,923.0,2014
563,125,9014615,East Fordham Road,Southern Boulevard,Bronx River Parkway,WB,09/20/2014,790.0,524.0,500.0,319.0,392.0,373.0,668.0,1142.0,1728.0,1795.0,1757.0,1825.0,1963.0,1916.0,2029.0,2181.0,2042.0,2014.0,2008.0,1959.0,1741.0,1444.0,1210.0,1110.0,2014
720,125,9014615,East Fordham Road,Southern Boulevard,Bronx River Parkway,WB,09/21/2014,915.0,686.0,527.0,415.0,418.0,356.0,440.0,624.0,860.0,1125.0,1540.0,1686.0,1714.0,1692.0,1661.0,1755.0,1774.0,1780.0,1823.0,1717.0,1526.0,1088.0,897.0,685.0,2014

In [78]:
test_df = new_df.groupby(["Segment ID","year"]).mean()

In [79]:
test_df

,,ID,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,10:00-11:00AM,11:00-12:00PM,12:00-1:00PM,1:00-2:00PM,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM
Segment ID,year,,,,,,,,,,,,,,,,,,,,,,,,,
202,2014,200.0,305.000000,222.000000,137.000000,138.000000,114.000000,155.000000,283.000000,355.000000,485.000000,549.000000,550.000000,555.000000,621.000000,630.000000,665.000000,649.000000,671.000000,700.000000,658.000000,646.000000,707.000000,620.000000,540.000000,504.000000
646,2012,779.5,28.250000,25.375000,19.000000,16.375000,26.375000,51.875000,97.250000,134.250000,182.750000,211.500000,200.875000,236.125000,250.375000,271.125000,263.625000,293.875000,290.750000,225.875000,183.000000,152.625000,94.875000,72.000000,43.000000,34.875000
1416,2015,290.0,61.722222,35.833333,19.388889,17.388889,26.388889,54.000000,118.000000,217.277778,246.222222,218.333333,261.555556,293.722222,312.055556,326.111111,352.833333,348.888889,346.888889,353.166667,319.611111,261.777778,210.333333,156.055556,113.666667,81.166667
1421,2012,670.5,53.750000,30.250000,21.750000,19.000000,25.125000,55.000000,151.500000,315.500000,353.375000,213.000000,219.625000,259.250000,287.125000,294.125000,352.125000,400.375000,395.375000,410.375000,366.250000,315.625000,183.625000,140.125000,87.875000,61.750000
1883,2012,686.0,57.000000,30.500000,19.000000,6.500000,19.500000,52.500000,134.500000,422.500000,352.000000,206.000000,207.000000,253.000000,289.000000,311.000000,367.000000,428.500000,379.500000,371.000000,325.000000,276.500000,223.000000,185.500000,119.500000,89.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9014615,2014,125.0,652.777778,473.777778,337.000000,252.888889,300.777778,445.000000,1368.111111,2364.444444,2401.777778,1972.000000,1733.888889,1761.111111,1793.333333,1802.555556,1987.222222,2151.888889,2167.333333,2181.666667,1990.444444,1803.444444,1511.555556,1162.333333,972.444444,821.777778
9014764,2014,135.0,1592.222222,1049.111111,798.888889,706.444444,768.333333,1264.111111,2587.888889,3070.444444,3149.333333,3156.777778,3050.333333,3144.888889,3203.222222,3348.777778,3573.555556,3420.555556,3463.888889,3577.111111,3552.111111,3339.333333,3183.555556,2876.777778,2636.000000,2023.888889
9017020,2014,5.0,370.000000,260.555556,192.888889,169.555556,188.333333,333.777778,832.555556,1077.222222,1019.777778,965.888889,940.222222,1038.444444,1046.666667,1095.666667,1159.666667,1110.222222,1201.111111,1228.888889,1201.000000,995.000000,779.333333,661.555556,610.000000,535.222222
9017037,2014,255.0,174.222222,111.333333,78.555556,68.000000,120.777778,329.555556,708.222222,976.666667,934.555556,893.111111,840.111111,820.111111,800.888889,757.777778,806.444444,777.777778,786.000000,741.222222,691.222222,602.444444,524.000000,416.666667,368.444444,267.222222
9017039,2014,255.0,260.777778,166.888889,125.333333,103.888889,113.888889,148.888889,259.666667,554.222222,823.666667,807.333333,717.888889,700.000000,752.666667,870.111111,1080.888889,1470.666667,1524.444444,1441.333333,1285.111111,1213.888889,875.222222,610.888889,455.333333,367.777778

In [80]:
test_df = test_df.sort_values(by=['Segment ID','year'], ascending=[True, True])

In [81]:
test_df.drop('ID', axis=1, inplace=True)

In [82]:
test_df

,,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,10:00-11:00AM,11:00-12:00PM,12:00-1:00PM,1:00-2:00PM,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM
Segment ID,year,,,,,,,,,,,,,,,,,,,,,,,,
202,2014,305.000000,222.000000,137.000000,138.000000,114.000000,155.000000,283.000000,355.000000,485.000000,549.000000,550.000000,555.000000,621.000000,630.000000,665.000000,649.000000,671.000000,700.000000,658.000000,646.000000,707.000000,620.000000,540.000000,504.000000
646,2012,28.250000,25.375000,19.000000,16.375000,26.375000,51.875000,97.250000,134.250000,182.750000,211.500000,200.875000,236.125000,250.375000,271.125000,263.625000,293.875000,290.750000,225.875000,183.000000,152.625000,94.875000,72.000000,43.000000,34.875000
1416,2015,61.722222,35.833333,19.388889,17.388889,26.388889,54.000000,118.000000,217.277778,246.222222,218.333333,261.555556,293.722222,312.055556,326.111111,352.833333,348.888889,346.888889,353.166667,319.611111,261.777778,210.333333,156.055556,113.666667,81.166667
1421,2012,53.750000,30.250000,21.750000,19.000000,25.125000,55.000000,151.500000,315.500000,353.375000,213.000000,219.625000,259.250000,287.125000,294.125000,352.125000,400.375000,395.375000,410.375000,366.250000,315.625000,183.625000,140.125000,87.875000,61.750000
1883,2012,57.000000,30.500000,19.000000,6.500000,19.500000,52.500000,134.500000,422.500000,352.000000,206.000000,207.000000,253.000000,289.000000,311.000000,367.000000,428.500000,379.500000,371.000000,325.000000,276.500000,223.000000,185.500000,119.500000,89.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9014615,2014,652.777778,473.777778,337.000000,252.888889,300.777778,445.000000,1368.111111,2364.444444,2401.777778,1972.000000,1733.888889,1761.111111,1793.333333,1802.555556,1987.222222,2151.888889,2167.333333,2181.666667,1990.444444,1803.444444,1511.555556,1162.333333,972.444444,821.777778
9014764,2014,1592.222222,1049.111111,798.888889,706.444444,768.333333,1264.111111,2587.888889,3070.444444,3149.333333,3156.777778,3050.333333,3144.888889,3203.222222,3348.777778,3573.555556,3420.555556,3463.888889,3577.111111,3552.111111,3339.333333,3183.555556,2876.777778,2636.000000,2023.888889
9017020,2014,370.000000,260.555556,192.888889,169.555556,188.333333,333.777778,832.555556,1077.222222,1019.777778,965.888889,940.222222,1038.444444,1046.666667,1095.666667,1159.666667,1110.222222,1201.111111,1228.888889,1201.000000,995.000000,779.333333,661.555556,610.000000,535.222222
9017037,2014,174.222222,111.333333,78.555556,68.000000,120.777778,329.555556,708.222222,976.666667,934.555556,893.111111,840.111111,820.111111,800.888889,757.777778,806.444444,777.777778,786.000000,741.222222,691.222222,602.444444,524.000000,416.666667,368.444444,267.222222
9017039,2014,260.777778,166.888889,125.333333,103.888889,113.888889,148.888889,259.666667,554.222222,823.666667,807.333333,717.888889,700.000000,752.666667,870.111111,1080.888889,1470.666667,1524.444444,1441.333333,1285.111111,1213.888889,875.222222,610.888889,455.333333,367.777778

In [83]:
test_df['total'] = test_df.sum(axis=1)

In [84]:
test_df

,,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,10:00-11:00AM,11:00-12:00PM,12:00-1:00PM,1:00-2:00PM,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM,total
Segment ID,year,,,,,,,,,,,,,,,,,,,,,,,,,
202,2014,305.000000,222.000000,137.000000,138.000000,114.000000,155.000000,283.000000,355.000000,485.000000,549.000000,550.000000,555.000000,621.000000,630.000000,665.000000,649.000000,671.000000,700.000000,658.000000,646.000000,707.000000,620.000000,540.000000,504.000000,11459.000000
646,2012,28.250000,25.375000,19.000000,16.375000,26.375000,51.875000,97.250000,134.250000,182.750000,211.500000,200.875000,236.125000,250.375000,271.125000,263.625000,293.875000,290.750000,225.875000,183.000000,152.625000,94.875000,72.000000,43.000000,34.875000,3406.000000
1416,2015,61.722222,35.833333,19.388889,17.388889,26.388889,54.000000,118.000000,217.277778,246.222222,218.333333,261.555556,293.722222,312.055556,326.111111,352.833333,348.888889,346.888889,353.166667,319.611111,261.777778,210.333333,156.055556,113.666667,81.166667,4752.388889
1421,2012,53.750000,30.250000,21.750000,19.000000,25.125000,55.000000,151.500000,315.500000,353.375000,213.000000,219.625000,259.250000,287.125000,294.125000,352.125000,400.375000,395.375000,410.375000,366.250000,315.625000,183.625000,140.125000,87.875000,61.750000,5011.875000
1883,2012,57.000000,30.500000,19.000000,6.500000,19.500000,52.500000,134.500000,422.500000,352.000000,206.000000,207.000000,253.000000,289.000000,311.000000,367.000000,428.500000,379.500000,371.000000,325.000000,276.500000,223.000000,185.500000,119.500000,89.000000,5124.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9014615,2014,652.777778,473.777778,337.000000,252.888889,300.777778,445.000000,1368.111111,2364.444444,2401.777778,1972.000000,1733.888889,1761.111111,1793.333333,1802.555556,1987.222222,2151.888889,2167.333333,2181.666667,1990.444444,1803.444444,1511.555556,1162.333333,972.444444,821.777778,34409.555556
9014764,2014,1592.222222,1049.111111,798.888889,706.444444,768.333333,1264.111111,2587.888889,3070.444444,3149.333333,3156.777778,3050.333333,3144.888889,3203.222222,3348.777778,3573.555556,3420.555556,3463.888889,3577.111111,3552.111111,3339.333333,3183.555556,2876.777778,2636.000000,2023.888889,62537.555556
9017020,2014,370.000000,260.555556,192.888889,169.555556,188.333333,333.777778,832.555556,1077.222222,1019.777778,965.888889,940.222222,1038.444444,1046.666667,1095.666667,1159.666667,1110.222222,1201.111111,1228.888889,1201.000000,995.000000,779.333333,661.555556,610.000000,535.222222,19013.555556
9017037,2014,174.222222,111.333333,78.555556,68.000000,120.777778,329.555556,708.222222,976.666667,934.555556,893.111111,840.111111,820.111111,800.888889,757.777778,806.444444,777.777778,786.000000,741.222222,691.222222,602.444444,524.000000,416.666667,368.444444,267.222222,13595.333333
9017039,2014,260.777778,166.888889,125.333333,103.888889,113.888889,148.888889,259.666667,554.222222,823.666667,807.333333,717.888889,700.000000,752.666667,870.111111,1080.888889,1470.666667,1524.444444,1441.333333,1285.111111,1213.888889,875.222222,610.888889,455.333333,367.777778,16730.777778

In [86]:
new_df[(new_df['Segment ID']  == 1883)]

,ID,Segment ID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,3:00-4:00AM,4:00-5:00AM,5:00-6:00AM,6:00-7:00AM,7:00-8:00AM,8:00-9:00AM,9:00-10:00AM,10:00-11:00AM,11:00-12:00PM,12:00-1:00PM,1:00-2:00PM,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM,year
684,684,1883,FOSTER ROAD,RAMONA AVENUE,RATHBUN AVENUE,NB,01/10/2012,64.0,36.0,22.0,10.0,17.0,42.0,84.0,318.0,305.0,186.0,171.0,253.0,294.0,311.0,392.0,489.0,424.0,433.0,383.0,320.0,296.0,229.0,123.0,109.0,2012
688,688,1883,FOSTER ROAD,RAMONA AVENUE,RATHBUN AVENUE,SB,01/10/2012,50.0,25.0,16.0,3.0,22.0,63.0,185.0,527.0,399.0,226.0,243.0,253.0,284.0,311.0,342.0,368.0,335.0,309.0,267.0,233.0,150.0,142.0,116.0,69.0,2012
9709,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,NB,10/24/2015,104.0,65.0,44.0,21.0,9.0,30.0,42.0,90.0,174.0,281.0,293.0,394.0,421.0,352.0,327.0,351.0,341.0,348.0,398.0,289.0,286.0,228.0,169.0,151.0,2015
9710,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,SB,10/24/2015,66.0,46.0,20.0,17.0,15.0,32.0,72.0,146.0,233.0,340.0,355.0,398.0,386.0,341.0,329.0,294.0,266.0,318.0,328.0,258.0,161.0,132.0,133.0,94.0,2015
9787,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,NB,10/25/2015,130.0,80.0,44.0,37.0,19.0,20.0,23.0,80.0,112.0,185.0,237.0,284.0,388.0,361.0,353.0,323.0,325.0,311.0,297.0,267.0,215.0,157.0,120.0,62.0,2015
9788,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,SB,10/25/2015,66.0,53.0,31.0,19.0,11.0,14.0,46.0,89.0,161.0,259.0,260.0,309.0,335.0,305.0,281.0,249.0,258.0,227.0,229.0,210.0,136.0,114.0,74.0,41.0,2015
9865,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,NB,10/26/2015,40.0,8.0,12.0,3.0,19.0,60.0,121.0,309.0,319.0,199.0,220.0,246.0,290.0,296.0,404.0,478.0,475.0,457.0,432.0,337.0,254.0,180.0,99.0,76.0,2015
9866,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,SB,10/26/2015,22.0,11.0,20.0,5.0,30.0,93.0,247.0,531.0,337.0,248.0,275.0,233.0,281.0,276.0,350.0,368.0,309.0,339.0,311.0,217.0,174.0,119.0,75.0,54.0,2015
9943,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,NB,10/27/2015,31.0,24.0,15.0,4.0,20.0,58.0,114.0,278.0,313.0,174.0,202.0,228.0,257.0,294.0,409.0,431.0,448.0,451.0,447.0,358.0,253.0,195.0,117.0,76.0,2015
9944,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,SB,10/27/2015,28.0,13.0,9.0,4.0,27.0,94.0,255.0,459.0,322.0,194.0,212.0,183.0,174.0,211.0,287.0,228.0,279.0,241.0,250.0,197.0,124.0,89.0,52.0,38.0,2015
10021,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,NB,10/28/2015,54.0,47.0,9.0,11.0,20.0,56.0,106.0,244.0,278.0,190.0,148.0,186.0,227.0,231.0,406.0,386.0,390.0,407.0,373.0,285.0,256.0,157.0,106.0,71.0,2015
10022,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,SB,10/28/2015,30.0,22.0,10.0,12.0,30.0,83.0,237.0,511.0,284.0,211.0,190.0,194.0,271.0,319.0,301.0,323.0,339.0,321.0,310.0,270.0,229.0,146.0,128.0,77.0,2015
10099,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,NB,10/29/2015,37.0,20.0,19.0,10.0,17.0,59.0,125.0,240.0,275.0,184.0,180.0,227.0,225.0,266.0,416.0,399.0,425.0,408.0,417.0,359.0,280.0,212.0,130.0,87.0,2015
10100,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,SB,10/29/2015,15.0,4.0,6.0,6.0,27.0,63.0,232.0,499.0,276.0,217.0,189.0,207.0,277.0,280.0,302.0,315.0,350.0,332.0,318.0,264.0,214.0,151.0,116.0,76.0,2015
10177,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,NB,10/30/2015,51.0,32.0,10.0,7.0,23.0,49.0,122.0,279.0,295.0,223.0,241.0,272.0,279.0,328.0,458.0,456.0,493.0,441.0,484.0,394.0,278.0,242.0,191.0,188.0,2015
10178,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,SB,10/30/2015,22.0,9.0,7.0,4.0,40.0,75.0,198.0,459.0,272.0,231.0,241.0,198.0,291.0,263.0,288.0,282.0,345.0,364.0,366.0,285.0,222.0,160.0,130.0,120.0,2015
10327,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,NB,10/31/2015,101.0,73.0,35.0,24.0,14.0,20.0,40.0,81.0,148.0,224.0,289.0,397.0,428.0,382.0,441.0,437.0,382.0,394.0,334.0,309.0,247.0,242.0,159.0,165.0,2015
10328,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,SB,10/31/2015,78.0,43.0,28.0,12.0,13.0,28.0,63.0,106.0,224.0,289.0,314.0,344.0,352.0,327.0,338.0,341.0,333.0,305.0,277.0,233.0,179.0,143.0,109.0,139.0,2015
10474,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,NB,11/01/2015,141.0,99.0,31.0,23.0,19.0,16.0,46.0,86.0,139.0,187.0,281.0,365.0,352.0,358.0,353.0,343.0,326.0,283.0,307.0,248.0,184.0,134.0,65.0,54.0,2015
10475,296,1883,FOSTER ROAD,RATHBUN AVENUE,RAMONA AVENUE,SB,11/01/2015,89.0,58.0,20.0,23.0,18.0,13.0,53.0,109.0,188.0,224.0,295.0,289.0,347.0,299.0,278.0,261.0,236.0,179.0,195.0,168.0,117.0,84.0,44.0,32.0,2015